version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .docker.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres:15
    env_file:
      - .docker.env
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /app/docker/database/extension.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  pgdata:
